/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.user.jooq;


import com.azure.csu.tiger.user.jooq.tables.CartDetail;
import com.azure.csu.tiger.user.jooq.tables.Favorite;
import com.azure.csu.tiger.user.jooq.tables.User;
import com.azure.csu.tiger.user.jooq.tables.UserAddress;
import com.azure.csu.tiger.user.jooq.tables.records.CartDetailRecord;
import com.azure.csu.tiger.user.jooq.tables.records.FavoriteRecord;
import com.azure.csu.tiger.user.jooq.tables.records.UserAddressRecord;
import com.azure.csu.tiger.user.jooq.tables.records.UserRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * user_center.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CartDetailRecord> KEY_CART_DETAIL_PRIMARY = Internal.createUniqueKey(CartDetail.CART_DETAIL, DSL.name("KEY_cart_detail_PRIMARY"), new TableField[] { CartDetail.CART_DETAIL.ID }, true);
    public static final UniqueKey<FavoriteRecord> KEY_FAVORITE_PRIMARY = Internal.createUniqueKey(Favorite.FAVORITE, DSL.name("KEY_favorite_PRIMARY"), new TableField[] { Favorite.FAVORITE.ID }, true);
    public static final UniqueKey<UserRecord> KEY_USER_PRIMARY = Internal.createUniqueKey(User.USER, DSL.name("KEY_user_PRIMARY"), new TableField[] { User.USER.ID }, true);
    public static final UniqueKey<UserAddressRecord> KEY_USER_ADDRESS_PRIMARY = Internal.createUniqueKey(UserAddress.USER_ADDRESS, DSL.name("KEY_user_address_PRIMARY"), new TableField[] { UserAddress.USER_ADDRESS.ID }, true);
}
