/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.user.jooq;


import com.azure.csu.tiger.user.jooq.tables.CartDetail;
import com.azure.csu.tiger.user.jooq.tables.Favorite;
import com.azure.csu.tiger.user.jooq.tables.User;
import com.azure.csu.tiger.user.jooq.tables.UserAddress;


/**
 * Convenience access to all tables in user_center.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * 购物车详情表
     */
    public static final CartDetail CART_DETAIL = CartDetail.CART_DETAIL;

    /**
     * 收藏表
     */
    public static final Favorite FAVORITE = Favorite.FAVORITE;

    /**
     * 用户表
     */
    public static final User USER = User.USER;

    /**
     * 用户地址表
     */
    public static final UserAddress USER_ADDRESS = UserAddress.USER_ADDRESS;
}
