/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.order.jooq;


import com.azure.csu.tiger.order.jooq.tables.OrderInfo;
import com.azure.csu.tiger.order.jooq.tables.OrderItem;
import com.azure.csu.tiger.order.jooq.tables.OrderOperationHistory;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrderCenter extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>order_center</code>
     */
    public static final OrderCenter ORDER_CENTER = new OrderCenter();

    /**
     * 订单表
     */
    public final OrderInfo ORDER_INFO = OrderInfo.ORDER_INFO;

    /**
     * 订单条目表
     */
    public final OrderItem ORDER_ITEM = OrderItem.ORDER_ITEM;

    /**
     * 订单操作记录表
     */
    public final OrderOperationHistory ORDER_OPERATION_HISTORY = OrderOperationHistory.ORDER_OPERATION_HISTORY;

    /**
     * No further instances allowed
     */
    private OrderCenter() {
        super("order_center", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.<Table<?>>asList(
            OrderInfo.ORDER_INFO,
            OrderItem.ORDER_ITEM,
            OrderOperationHistory.ORDER_OPERATION_HISTORY);
    }
}
