spring:
  datasource:
    url: jdbc:mysql://emall.mysql.database.azure.com:3306/product_center
    username: emall
    password: Q1w2e3r4t5y6
  redis:
    database: 0
    host: sheintest.redis.cache.windows.net
    port: 6379
    password: DFALHzmo7mAkMYxTCrrOqwuepRKLYIEhIAzCaAzmkg4=
    jedis:
      pool:
        enable: true
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1
    connect-timeout: 30000

