kind: Service
apiVersion: v1
metadata:
  name: emall-web
  namespace: emall
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: emall-web
  type: LoadBalancer