kind: Deployment
apiVersion: apps/v1
metadata:
  name: emall-web
  namespace: emall
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emall-web
  template:
    metadata:
      labels:
        app: emall-web
    spec:
      containers:
        - name: emall-web
          image: acrmall.azurecr.io/emall-web:v0.6
          resources:
            limits:
              cpu: 2
              memory: 1024Mi
            requests:
              cpu: 2
              memory: 1024Mi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
---
kind: Service
apiVersion: v1
metadata:
  name: emall-web
  namespace: emall
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: emall-web
  type: LoadBalancer