/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.product.jooq.tables;


import com.azure.csu.tiger.product.jooq.Keys;
import com.azure.csu.tiger.product.jooq.ProductCenter;
import com.azure.csu.tiger.product.jooq.tables.records.AttributeEnumRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 属性枚举值表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AttributeEnum extends TableImpl<AttributeEnumRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>product_center.attribute_enum</code>
     */
    public static final AttributeEnum ATTRIBUTE_ENUM = new AttributeEnum();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AttributeEnumRecord> getRecordType() {
        return AttributeEnumRecord.class;
    }

    /**
     * The column <code>product_center.attribute_enum.id</code>.
     */
    public final TableField<AttributeEnumRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>product_center.attribute_enum.attribute_id</code>. 属性id
     */
    public final TableField<AttributeEnumRecord, Long> ATTRIBUTE_ID = createField(DSL.name("attribute_id"), SQLDataType.BIGINT.nullable(false), this, "属性id");

    /**
     * The column <code>product_center.attribute_enum.value</code>. 属性枚举值
     */
    public final TableField<AttributeEnumRecord, String> VALUE = createField(DSL.name("value"), SQLDataType.VARCHAR(255).nullable(false), this, "属性枚举值");

    /**
     * The column <code>product_center.attribute_enum.sort</code>. 同属性不同枚举值排序
     */
    public final TableField<AttributeEnumRecord, Integer> SORT = createField(DSL.name("sort"), SQLDataType.INTEGER.defaultValue(DSL.inline("0", SQLDataType.INTEGER)), this, "同属性不同枚举值排序");

    /**
     * The column <code>product_center.attribute_enum.create_time</code>.
     */
    public final TableField<AttributeEnumRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>product_center.attribute_enum.modify_time</code>.
     */
    public final TableField<AttributeEnumRecord, LocalDateTime> MODIFY_TIME = createField(DSL.name("modify_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>product_center.attribute_enum.create_user_id</code>.
     */
    public final TableField<AttributeEnumRecord, Long> CREATE_USER_ID = createField(DSL.name("create_user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>product_center.attribute_enum.modify_user_id</code>.
     */
    public final TableField<AttributeEnumRecord, Long> MODIFY_USER_ID = createField(DSL.name("modify_user_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private AttributeEnum(Name alias, Table<AttributeEnumRecord> aliased) {
        this(alias, aliased, null);
    }

    private AttributeEnum(Name alias, Table<AttributeEnumRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("属性枚举值表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>product_center.attribute_enum</code> table reference
     */
    public AttributeEnum(String alias) {
        this(DSL.name(alias), ATTRIBUTE_ENUM);
    }

    /**
     * Create an aliased <code>product_center.attribute_enum</code> table reference
     */
    public AttributeEnum(Name alias) {
        this(alias, ATTRIBUTE_ENUM);
    }

    /**
     * Create a <code>product_center.attribute_enum</code> table reference
     */
    public AttributeEnum() {
        this(DSL.name("attribute_enum"), null);
    }

    public <O extends Record> AttributeEnum(Table<O> child, ForeignKey<O, AttributeEnumRecord> key) {
        super(child, key, ATTRIBUTE_ENUM);
    }

    @Override
    public Schema getSchema() {
        return ProductCenter.PRODUCT_CENTER;
    }

    @Override
    public Identity<AttributeEnumRecord, Long> getIdentity() {
        return (Identity<AttributeEnumRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AttributeEnumRecord> getPrimaryKey() {
        return Keys.KEY_ATTRIBUTE_ENUM_PRIMARY;
    }

    @Override
    public List<UniqueKey<AttributeEnumRecord>> getKeys() {
        return Arrays.<UniqueKey<AttributeEnumRecord>>asList(Keys.KEY_ATTRIBUTE_ENUM_PRIMARY);
    }

    @Override
    public AttributeEnum as(String alias) {
        return new AttributeEnum(DSL.name(alias), this);
    }

    @Override
    public AttributeEnum as(Name alias) {
        return new AttributeEnum(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public AttributeEnum rename(String name) {
        return new AttributeEnum(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AttributeEnum rename(Name name) {
        return new AttributeEnum(name, null);
    }

    // -------------------------------------------------------------------------
    // Row8 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, String, Integer, LocalDateTime, LocalDateTime, Long, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }
}
