/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.user.jooq.tables;


import com.azure.csu.tiger.user.jooq.Keys;
import com.azure.csu.tiger.user.jooq.UserCenter;
import com.azure.csu.tiger.user.jooq.tables.records.FavoriteRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row4;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * 收藏表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Favorite extends TableImpl<FavoriteRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>user_center.favorite</code>
     */
    public static final Favorite FAVORITE = new Favorite();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FavoriteRecord> getRecordType() {
        return FavoriteRecord.class;
    }

    /**
     * The column <code>user_center.favorite.id</code>.
     */
    public final TableField<FavoriteRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>user_center.favorite.user_id</code>. 用户id
     */
    public final TableField<FavoriteRecord, Long> USER_ID = createField(DSL.name("user_id"), SQLDataType.BIGINT.nullable(false), this, "用户id");

    /**
     * The column <code>user_center.favorite.sku_id</code>. 商品id
     */
    public final TableField<FavoriteRecord, Long> SKU_ID = createField(DSL.name("sku_id"), SQLDataType.BIGINT.nullable(false), this, "商品id");

    /**
     * The column <code>user_center.favorite.create_time</code>.
     */
    public final TableField<FavoriteRecord, LocalDateTime> CREATE_TIME = createField(DSL.name("create_time"), SQLDataType.LOCALDATETIME(0).defaultValue(DSL.field("CURRENT_TIMESTAMP", SQLDataType.LOCALDATETIME)), this, "");

    private Favorite(Name alias, Table<FavoriteRecord> aliased) {
        this(alias, aliased, null);
    }

    private Favorite(Name alias, Table<FavoriteRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment("收藏表"), TableOptions.table());
    }

    /**
     * Create an aliased <code>user_center.favorite</code> table reference
     */
    public Favorite(String alias) {
        this(DSL.name(alias), FAVORITE);
    }

    /**
     * Create an aliased <code>user_center.favorite</code> table reference
     */
    public Favorite(Name alias) {
        this(alias, FAVORITE);
    }

    /**
     * Create a <code>user_center.favorite</code> table reference
     */
    public Favorite() {
        this(DSL.name("favorite"), null);
    }

    public <O extends Record> Favorite(Table<O> child, ForeignKey<O, FavoriteRecord> key) {
        super(child, key, FAVORITE);
    }

    @Override
    public Schema getSchema() {
        return UserCenter.USER_CENTER;
    }

    @Override
    public Identity<FavoriteRecord, Long> getIdentity() {
        return (Identity<FavoriteRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<FavoriteRecord> getPrimaryKey() {
        return Keys.KEY_FAVORITE_PRIMARY;
    }

    @Override
    public List<UniqueKey<FavoriteRecord>> getKeys() {
        return Arrays.<UniqueKey<FavoriteRecord>>asList(Keys.KEY_FAVORITE_PRIMARY);
    }

    @Override
    public Favorite as(String alias) {
        return new Favorite(DSL.name(alias), this);
    }

    @Override
    public Favorite as(Name alias) {
        return new Favorite(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Favorite rename(String name) {
        return new Favorite(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Favorite rename(Name name) {
        return new Favorite(name, null);
    }

    // -------------------------------------------------------------------------
    // Row4 type methods
    // -------------------------------------------------------------------------

    @Override
    public Row4<Long, Long, Long, LocalDateTime> fieldsRow() {
        return (Row4) super.fieldsRow();
    }
}
