/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.product.jooq.tables.records;


import com.azure.csu.tiger.product.jooq.tables.CouponUsed;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 优惠券使用记录表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CouponUsedRecord extends UpdatableRecordImpl<CouponUsedRecord> implements Record7<Long, Long, Long, Long, Long, Long, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>product_center.coupon_used.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>product_center.coupon_used.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>product_center.coupon_used.coupon_id</code>. 优惠券id
     */
    public void setCouponId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>product_center.coupon_used.coupon_id</code>. 优惠券id
     */
    public Long getCouponId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>product_center.coupon_used.coupon_taken_id</code>. 优惠券领用id
     */
    public void setCouponTakenId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>product_center.coupon_used.coupon_taken_id</code>. 优惠券领用id
     */
    public Long getCouponTakenId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>product_center.coupon_used.user_id</code>. 用户id
     */
    public void setUserId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>product_center.coupon_used.user_id</code>. 用户id
     */
    public Long getUserId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>product_center.coupon_used.order_id</code>. 订单id
     */
    public void setOrderId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>product_center.coupon_used.order_id</code>. 订单id
     */
    public Long getOrderId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>product_center.coupon_used.used_num</code>. 使用次数-通常每种优惠券一次使用一张
     */
    public void setUsedNum(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>product_center.coupon_used.used_num</code>. 使用次数-通常每种优惠券一次使用一张
     */
    public Long getUsedNum() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>product_center.coupon_used.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>product_center.coupon_used.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row7<Long, Long, Long, Long, Long, Long, LocalDateTime> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    @Override
    public Row7<Long, Long, Long, Long, Long, Long, LocalDateTime> valuesRow() {
        return (Row7) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CouponUsed.COUPON_USED.ID;
    }

    @Override
    public Field<Long> field2() {
        return CouponUsed.COUPON_USED.COUPON_ID;
    }

    @Override
    public Field<Long> field3() {
        return CouponUsed.COUPON_USED.COUPON_TAKEN_ID;
    }

    @Override
    public Field<Long> field4() {
        return CouponUsed.COUPON_USED.USER_ID;
    }

    @Override
    public Field<Long> field5() {
        return CouponUsed.COUPON_USED.ORDER_ID;
    }

    @Override
    public Field<Long> field6() {
        return CouponUsed.COUPON_USED.USED_NUM;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return CouponUsed.COUPON_USED.CREATE_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCouponId();
    }

    @Override
    public Long component3() {
        return getCouponTakenId();
    }

    @Override
    public Long component4() {
        return getUserId();
    }

    @Override
    public Long component5() {
        return getOrderId();
    }

    @Override
    public Long component6() {
        return getUsedNum();
    }

    @Override
    public LocalDateTime component7() {
        return getCreateTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCouponId();
    }

    @Override
    public Long value3() {
        return getCouponTakenId();
    }

    @Override
    public Long value4() {
        return getUserId();
    }

    @Override
    public Long value5() {
        return getOrderId();
    }

    @Override
    public Long value6() {
        return getUsedNum();
    }

    @Override
    public LocalDateTime value7() {
        return getCreateTime();
    }

    @Override
    public CouponUsedRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CouponUsedRecord value2(Long value) {
        setCouponId(value);
        return this;
    }

    @Override
    public CouponUsedRecord value3(Long value) {
        setCouponTakenId(value);
        return this;
    }

    @Override
    public CouponUsedRecord value4(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public CouponUsedRecord value5(Long value) {
        setOrderId(value);
        return this;
    }

    @Override
    public CouponUsedRecord value6(Long value) {
        setUsedNum(value);
        return this;
    }

    @Override
    public CouponUsedRecord value7(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public CouponUsedRecord values(Long value1, Long value2, Long value3, Long value4, Long value5, Long value6, LocalDateTime value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CouponUsedRecord
     */
    public CouponUsedRecord() {
        super(CouponUsed.COUPON_USED);
    }

    /**
     * Create a detached, initialised CouponUsedRecord
     */
    public CouponUsedRecord(Long id, Long couponId, Long couponTakenId, Long userId, Long orderId, Long usedNum, LocalDateTime createTime) {
        super(CouponUsed.COUPON_USED);

        setId(id);
        setCouponId(couponId);
        setCouponTakenId(couponTakenId);
        setUserId(userId);
        setOrderId(orderId);
        setUsedNum(usedNum);
        setCreateTime(createTime);
    }
}
