/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.product.jooq.tables.records;


import com.azure.csu.tiger.product.jooq.tables.CouponRange;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 优惠券适用范围表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CouponRangeRecord extends UpdatableRecordImpl<CouponRangeRecord> implements Record8<Long, Long, Byte, Long, LocalDateTime, LocalDateTime, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>product_center.coupon_range.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>product_center.coupon_range.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>product_center.coupon_range.coupon_id</code>. 优惠券id
     */
    public void setCouponId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>product_center.coupon_range.coupon_id</code>. 优惠券id
     */
    public Long getCouponId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>product_center.coupon_range.range_type</code>. 全场-0, 分类-1, 商品-2, 品牌-3
     */
    public void setRangeType(Byte value) {
        set(2, value);
    }

    /**
     * Getter for <code>product_center.coupon_range.range_type</code>. 全场-0, 分类-1, 商品-2, 品牌-3
     */
    public Byte getRangeType() {
        return (Byte) get(2);
    }

    /**
     * Setter for <code>product_center.coupon_range.range_id</code>. 适用范围id
     */
    public void setRangeId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>product_center.coupon_range.range_id</code>. 适用范围id
     */
    public Long getRangeId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>product_center.coupon_range.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>product_center.coupon_range.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>product_center.coupon_range.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>product_center.coupon_range.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>product_center.coupon_range.create_user_id</code>.
     */
    public void setCreateUserId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>product_center.coupon_range.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>product_center.coupon_range.modify_user_id</code>.
     */
    public void setModifyUserId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>product_center.coupon_range.modify_user_id</code>.
     */
    public Long getModifyUserId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, Byte, Long, LocalDateTime, LocalDateTime, Long, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, Byte, Long, LocalDateTime, LocalDateTime, Long, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CouponRange.COUPON_RANGE.ID;
    }

    @Override
    public Field<Long> field2() {
        return CouponRange.COUPON_RANGE.COUPON_ID;
    }

    @Override
    public Field<Byte> field3() {
        return CouponRange.COUPON_RANGE.RANGE_TYPE;
    }

    @Override
    public Field<Long> field4() {
        return CouponRange.COUPON_RANGE.RANGE_ID;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return CouponRange.COUPON_RANGE.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return CouponRange.COUPON_RANGE.MODIFY_TIME;
    }

    @Override
    public Field<Long> field7() {
        return CouponRange.COUPON_RANGE.CREATE_USER_ID;
    }

    @Override
    public Field<Long> field8() {
        return CouponRange.COUPON_RANGE.MODIFY_USER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getCouponId();
    }

    @Override
    public Byte component3() {
        return getRangeType();
    }

    @Override
    public Long component4() {
        return getRangeId();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component6() {
        return getModifyTime();
    }

    @Override
    public Long component7() {
        return getCreateUserId();
    }

    @Override
    public Long component8() {
        return getModifyUserId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getCouponId();
    }

    @Override
    public Byte value3() {
        return getRangeType();
    }

    @Override
    public Long value4() {
        return getRangeId();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value6() {
        return getModifyTime();
    }

    @Override
    public Long value7() {
        return getCreateUserId();
    }

    @Override
    public Long value8() {
        return getModifyUserId();
    }

    @Override
    public CouponRangeRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CouponRangeRecord value2(Long value) {
        setCouponId(value);
        return this;
    }

    @Override
    public CouponRangeRecord value3(Byte value) {
        setRangeType(value);
        return this;
    }

    @Override
    public CouponRangeRecord value4(Long value) {
        setRangeId(value);
        return this;
    }

    @Override
    public CouponRangeRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public CouponRangeRecord value6(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public CouponRangeRecord value7(Long value) {
        setCreateUserId(value);
        return this;
    }

    @Override
    public CouponRangeRecord value8(Long value) {
        setModifyUserId(value);
        return this;
    }

    @Override
    public CouponRangeRecord values(Long value1, Long value2, Byte value3, Long value4, LocalDateTime value5, LocalDateTime value6, Long value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CouponRangeRecord
     */
    public CouponRangeRecord() {
        super(CouponRange.COUPON_RANGE);
    }

    /**
     * Create a detached, initialised CouponRangeRecord
     */
    public CouponRangeRecord(Long id, Long couponId, Byte rangeType, Long rangeId, LocalDateTime createTime, LocalDateTime modifyTime, Long createUserId, Long modifyUserId) {
        super(CouponRange.COUPON_RANGE);

        setId(id);
        setCouponId(couponId);
        setRangeType(rangeType);
        setRangeId(rangeId);
        setCreateTime(createTime);
        setModifyTime(modifyTime);
        setCreateUserId(createUserId);
        setModifyUserId(modifyUserId);
    }
}
