/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.product.jooq.tables.records;


import com.azure.csu.tiger.product.jooq.tables.SkuAttributeValue;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * SKU属性值表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SkuAttributeValueRecord extends UpdatableRecordImpl<SkuAttributeValueRecord> implements Record8<Long, Long, Long, String, LocalDateTime, LocalDateTime, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>product_center.sku_attribute_value.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>product_center.sku_attribute_value.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>product_center.sku_attribute_value.sku_id</code>. SKU id
     */
    public void setSkuId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>product_center.sku_attribute_value.sku_id</code>. SKU id
     */
    public Long getSkuId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>product_center.sku_attribute_value.attribute_id</code>. 属性id
     */
    public void setAttributeId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>product_center.sku_attribute_value.attribute_id</code>. 属性id
     */
    public Long getAttributeId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>product_center.sku_attribute_value.value</code>. 属性值
     */
    public void setValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>product_center.sku_attribute_value.value</code>. 属性值
     */
    public String getValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>product_center.sku_attribute_value.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>product_center.sku_attribute_value.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>product_center.sku_attribute_value.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>product_center.sku_attribute_value.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>product_center.sku_attribute_value.create_user_id</code>.
     */
    public void setCreateUserId(Long value) {
        set(6, value);
    }

    /**
     * Getter for <code>product_center.sku_attribute_value.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(6);
    }

    /**
     * Setter for <code>product_center.sku_attribute_value.modify_user_id</code>.
     */
    public void setModifyUserId(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>product_center.sku_attribute_value.modify_user_id</code>.
     */
    public Long getModifyUserId() {
        return (Long) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<Long, Long, Long, String, LocalDateTime, LocalDateTime, Long, Long> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<Long, Long, Long, String, LocalDateTime, LocalDateTime, Long, Long> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SkuAttributeValue.SKU_ATTRIBUTE_VALUE.ID;
    }

    @Override
    public Field<Long> field2() {
        return SkuAttributeValue.SKU_ATTRIBUTE_VALUE.SKU_ID;
    }

    @Override
    public Field<Long> field3() {
        return SkuAttributeValue.SKU_ATTRIBUTE_VALUE.ATTRIBUTE_ID;
    }

    @Override
    public Field<String> field4() {
        return SkuAttributeValue.SKU_ATTRIBUTE_VALUE.VALUE;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return SkuAttributeValue.SKU_ATTRIBUTE_VALUE.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return SkuAttributeValue.SKU_ATTRIBUTE_VALUE.MODIFY_TIME;
    }

    @Override
    public Field<Long> field7() {
        return SkuAttributeValue.SKU_ATTRIBUTE_VALUE.CREATE_USER_ID;
    }

    @Override
    public Field<Long> field8() {
        return SkuAttributeValue.SKU_ATTRIBUTE_VALUE.MODIFY_USER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getSkuId();
    }

    @Override
    public Long component3() {
        return getAttributeId();
    }

    @Override
    public String component4() {
        return getValue();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component6() {
        return getModifyTime();
    }

    @Override
    public Long component7() {
        return getCreateUserId();
    }

    @Override
    public Long component8() {
        return getModifyUserId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getSkuId();
    }

    @Override
    public Long value3() {
        return getAttributeId();
    }

    @Override
    public String value4() {
        return getValue();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value6() {
        return getModifyTime();
    }

    @Override
    public Long value7() {
        return getCreateUserId();
    }

    @Override
    public Long value8() {
        return getModifyUserId();
    }

    @Override
    public SkuAttributeValueRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SkuAttributeValueRecord value2(Long value) {
        setSkuId(value);
        return this;
    }

    @Override
    public SkuAttributeValueRecord value3(Long value) {
        setAttributeId(value);
        return this;
    }

    @Override
    public SkuAttributeValueRecord value4(String value) {
        setValue(value);
        return this;
    }

    @Override
    public SkuAttributeValueRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SkuAttributeValueRecord value6(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public SkuAttributeValueRecord value7(Long value) {
        setCreateUserId(value);
        return this;
    }

    @Override
    public SkuAttributeValueRecord value8(Long value) {
        setModifyUserId(value);
        return this;
    }

    @Override
    public SkuAttributeValueRecord values(Long value1, Long value2, Long value3, String value4, LocalDateTime value5, LocalDateTime value6, Long value7, Long value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SkuAttributeValueRecord
     */
    public SkuAttributeValueRecord() {
        super(SkuAttributeValue.SKU_ATTRIBUTE_VALUE);
    }

    /**
     * Create a detached, initialised SkuAttributeValueRecord
     */
    public SkuAttributeValueRecord(Long id, Long skuId, Long attributeId, String value, LocalDateTime createTime, LocalDateTime modifyTime, Long createUserId, Long modifyUserId) {
        super(SkuAttributeValue.SKU_ATTRIBUTE_VALUE);

        setId(id);
        setSkuId(skuId);
        setAttributeId(attributeId);
        setValue(value);
        setCreateTime(createTime);
        setModifyTime(modifyTime);
        setCreateUserId(createUserId);
        setModifyUserId(modifyUserId);
    }
}
