/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.product.jooq.tables.records;


import com.azure.csu.tiger.product.jooq.tables.SkuImage;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 商品图片表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SkuImageRecord extends UpdatableRecordImpl<SkuImageRecord> implements Record5<Long, Long, String, LocalDateTime, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>product_center.sku_image.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>product_center.sku_image.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>product_center.sku_image.sku_id</code>. SKU id
     */
    public void setSkuId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>product_center.sku_image.sku_id</code>. SKU id
     */
    public Long getSkuId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>product_center.sku_image.img_url</code>. logo地址
     */
    public void setImgUrl(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>product_center.sku_image.img_url</code>. logo地址
     */
    public String getImgUrl() {
        return (String) get(2);
    }

    /**
     * Setter for <code>product_center.sku_image.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>product_center.sku_image.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>product_center.sku_image.create_user_id</code>.
     */
    public void setCreateUserId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>product_center.sku_image.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row5<Long, Long, String, LocalDateTime, Long> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    @Override
    public Row5<Long, Long, String, LocalDateTime, Long> valuesRow() {
        return (Row5) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return SkuImage.SKU_IMAGE.ID;
    }

    @Override
    public Field<Long> field2() {
        return SkuImage.SKU_IMAGE.SKU_ID;
    }

    @Override
    public Field<String> field3() {
        return SkuImage.SKU_IMAGE.IMG_URL;
    }

    @Override
    public Field<LocalDateTime> field4() {
        return SkuImage.SKU_IMAGE.CREATE_TIME;
    }

    @Override
    public Field<Long> field5() {
        return SkuImage.SKU_IMAGE.CREATE_USER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getSkuId();
    }

    @Override
    public String component3() {
        return getImgUrl();
    }

    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    @Override
    public Long component5() {
        return getCreateUserId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getSkuId();
    }

    @Override
    public String value3() {
        return getImgUrl();
    }

    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    @Override
    public Long value5() {
        return getCreateUserId();
    }

    @Override
    public SkuImageRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public SkuImageRecord value2(Long value) {
        setSkuId(value);
        return this;
    }

    @Override
    public SkuImageRecord value3(String value) {
        setImgUrl(value);
        return this;
    }

    @Override
    public SkuImageRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public SkuImageRecord value5(Long value) {
        setCreateUserId(value);
        return this;
    }

    @Override
    public SkuImageRecord values(Long value1, Long value2, String value3, LocalDateTime value4, Long value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SkuImageRecord
     */
    public SkuImageRecord() {
        super(SkuImage.SKU_IMAGE);
    }

    /**
     * Create a detached, initialised SkuImageRecord
     */
    public SkuImageRecord(Long id, Long skuId, String imgUrl, LocalDateTime createTime, Long createUserId) {
        super(SkuImage.SKU_IMAGE);

        setId(id);
        setSkuId(skuId);
        setImgUrl(imgUrl);
        setCreateTime(createTime);
        setCreateUserId(createUserId);
    }
}
