kind: Deployment
apiVersion: apps/v1
metadata:
  name: emall-user
  namespace: emall
spec:
  replicas: 3
  selector:
    matchLabels:
      app: emall-user
  template:
    metadata:
      labels:
        app: emall-user
    spec:
      containers:
        - name: emall-user
          image: acrmall.azurecr.io/emall-user:v0.3
          resources:
            limits:
              cpu: 2
              memory: 1024Mi
            requests:
              cpu: 2
              memory: 1024Mi
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler