// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.azure.csu.tiger.grpc.lib;

public interface AddCartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:AddCartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uid = 1;</code>
   * @return The uid.
   */
  long getUid();

  /**
   * <code>int64 skuId = 2;</code>
   * @return The skuId.
   */
  long getSkuId();

  /**
   * <code>.SkuInfo skuInfo = 3;</code>
   * @return Whether the skuInfo field is set.
   */
  boolean hasSkuInfo();
  /**
   * <code>.SkuInfo skuInfo = 3;</code>
   * @return The skuInfo.
   */
  com.azure.csu.tiger.grpc.lib.SkuInfo getSkuInfo();
  /**
   * <code>.SkuInfo skuInfo = 3;</code>
   */
  com.azure.csu.tiger.grpc.lib.SkuInfoOrBuilder getSkuInfoOrBuilder();
}
