// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.azure.csu.tiger.grpc.lib;

public final class BaseProto {
  private BaseProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SkuInfo_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SkuInfo_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SkuInfo_AttrEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SkuInfo_AttrEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nbase.proto\"\266\001\n\007SkuInfo\022\r\n\005skuId\030\001 \001(\003\022" +
      "\r\n\005spuId\030\002 \001(\003\022\014\n\004name\030\003 \001(\t\022\022\n\ncategory" +
      "Id\030\004 \001(\003\022\r\n\005price\030\005 \001(\003\022\r\n\005stock\030\006 \001(\003\022 " +
      "\n\004attr\030\007 \003(\0132\022.SkuInfo.AttrEntry\032+\n\tAttr" +
      "Entry\022\013\n\003key\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B+\n" +
      "\034com.azure.csu.tiger.grpc.libB\tBaseProto" +
      "P\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_SkuInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SkuInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SkuInfo_descriptor,
        new java.lang.String[] { "SkuId", "SpuId", "Name", "CategoryId", "Price", "Stock", "Attr", });
    internal_static_SkuInfo_AttrEntry_descriptor =
      internal_static_SkuInfo_descriptor.getNestedTypes().get(0);
    internal_static_SkuInfo_AttrEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SkuInfo_AttrEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
