// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.azure.csu.tiger.grpc.lib;

public interface CategoryListResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:CategoryListResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .Category datas = 1;</code>
   */
  java.util.List<com.azure.csu.tiger.grpc.lib.Category> 
      getDatasList();
  /**
   * <code>repeated .Category datas = 1;</code>
   */
  com.azure.csu.tiger.grpc.lib.Category getDatas(int index);
  /**
   * <code>repeated .Category datas = 1;</code>
   */
  int getDatasCount();
  /**
   * <code>repeated .Category datas = 1;</code>
   */
  java.util.List<? extends com.azure.csu.tiger.grpc.lib.CategoryOrBuilder> 
      getDatasOrBuilderList();
  /**
   * <code>repeated .Category datas = 1;</code>
   */
  com.azure.csu.tiger.grpc.lib.CategoryOrBuilder getDatasOrBuilder(
      int index);
}
