// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.azure.csu.tiger.grpc.lib;

public interface ClearCartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ClearCartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 uid = 1;</code>
   * @return The uid.
   */
  long getUid();
}
