// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.azure.csu.tiger.grpc.lib;

/**
 * Protobuf type {@code CreateOrderRequest}
 */
public final class CreateOrderRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:CreateOrderRequest)
    CreateOrderRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateOrderRequest.newBuilder() to construct.
  private CreateOrderRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateOrderRequest() {
    comment_ = "";
    skuData_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new CreateOrderRequest();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateOrderRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            userId_ = input.readInt64();
            break;
          }
          case 16: {

            addressId_ = input.readInt64();
            break;
          }
          case 24: {

            sourceType_ = input.readInt32();
            break;
          }
          case 32: {

            totalAmount_ = input.readInt64();
            break;
          }
          case 40: {

            couponAmount_ = input.readInt64();
            break;
          }
          case 48: {

            shippingAmount_ = input.readInt64();
            break;
          }
          case 56: {

            payAmount_ = input.readInt64();
            break;
          }
          case 66: {
            java.lang.String s = input.readStringRequireUtf8();

            comment_ = s;
            break;
          }
          case 74: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              skuData_ = new java.util.ArrayList<com.azure.csu.tiger.grpc.lib.OrderItemSku>();
              mutable_bitField0_ |= 0x00000001;
            }
            skuData_.add(
                input.readMessage(com.azure.csu.tiger.grpc.lib.OrderItemSku.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        skuData_ = java.util.Collections.unmodifiableList(skuData_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.azure.csu.tiger.grpc.lib.OrderProto.internal_static_CreateOrderRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.azure.csu.tiger.grpc.lib.OrderProto.internal_static_CreateOrderRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.azure.csu.tiger.grpc.lib.CreateOrderRequest.class, com.azure.csu.tiger.grpc.lib.CreateOrderRequest.Builder.class);
  }

  public static final int USERID_FIELD_NUMBER = 1;
  private long userId_;
  /**
   * <code>int64 userId = 1;</code>
   * @return The userId.
   */
  @java.lang.Override
  public long getUserId() {
    return userId_;
  }

  public static final int ADDRESSID_FIELD_NUMBER = 2;
  private long addressId_;
  /**
   * <code>int64 addressId = 2;</code>
   * @return The addressId.
   */
  @java.lang.Override
  public long getAddressId() {
    return addressId_;
  }

  public static final int SOURCETYPE_FIELD_NUMBER = 3;
  private int sourceType_;
  /**
   * <code>int32 sourceType = 3;</code>
   * @return The sourceType.
   */
  @java.lang.Override
  public int getSourceType() {
    return sourceType_;
  }

  public static final int TOTALAMOUNT_FIELD_NUMBER = 4;
  private long totalAmount_;
  /**
   * <code>int64 totalAmount = 4;</code>
   * @return The totalAmount.
   */
  @java.lang.Override
  public long getTotalAmount() {
    return totalAmount_;
  }

  public static final int COUPONAMOUNT_FIELD_NUMBER = 5;
  private long couponAmount_;
  /**
   * <code>int64 couponAmount = 5;</code>
   * @return The couponAmount.
   */
  @java.lang.Override
  public long getCouponAmount() {
    return couponAmount_;
  }

  public static final int SHIPPINGAMOUNT_FIELD_NUMBER = 6;
  private long shippingAmount_;
  /**
   * <code>int64 shippingAmount = 6;</code>
   * @return The shippingAmount.
   */
  @java.lang.Override
  public long getShippingAmount() {
    return shippingAmount_;
  }

  public static final int PAYAMOUNT_FIELD_NUMBER = 7;
  private long payAmount_;
  /**
   * <code>int64 payAmount = 7;</code>
   * @return The payAmount.
   */
  @java.lang.Override
  public long getPayAmount() {
    return payAmount_;
  }

  public static final int COMMENT_FIELD_NUMBER = 8;
  private volatile java.lang.Object comment_;
  /**
   * <code>string comment = 8;</code>
   * @return The comment.
   */
  @java.lang.Override
  public java.lang.String getComment() {
    java.lang.Object ref = comment_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comment_ = s;
      return s;
    }
  }
  /**
   * <code>string comment = 8;</code>
   * @return The bytes for comment.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getCommentBytes() {
    java.lang.Object ref = comment_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comment_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SKUDATA_FIELD_NUMBER = 9;
  private java.util.List<com.azure.csu.tiger.grpc.lib.OrderItemSku> skuData_;
  /**
   * <code>repeated .OrderItemSku skuData = 9;</code>
   */
  @java.lang.Override
  public java.util.List<com.azure.csu.tiger.grpc.lib.OrderItemSku> getSkuDataList() {
    return skuData_;
  }
  /**
   * <code>repeated .OrderItemSku skuData = 9;</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.azure.csu.tiger.grpc.lib.OrderItemSkuOrBuilder> 
      getSkuDataOrBuilderList() {
    return skuData_;
  }
  /**
   * <code>repeated .OrderItemSku skuData = 9;</code>
   */
  @java.lang.Override
  public int getSkuDataCount() {
    return skuData_.size();
  }
  /**
   * <code>repeated .OrderItemSku skuData = 9;</code>
   */
  @java.lang.Override
  public com.azure.csu.tiger.grpc.lib.OrderItemSku getSkuData(int index) {
    return skuData_.get(index);
  }
  /**
   * <code>repeated .OrderItemSku skuData = 9;</code>
   */
  @java.lang.Override
  public com.azure.csu.tiger.grpc.lib.OrderItemSkuOrBuilder getSkuDataOrBuilder(
      int index) {
    return skuData_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (userId_ != 0L) {
      output.writeInt64(1, userId_);
    }
    if (addressId_ != 0L) {
      output.writeInt64(2, addressId_);
    }
    if (sourceType_ != 0) {
      output.writeInt32(3, sourceType_);
    }
    if (totalAmount_ != 0L) {
      output.writeInt64(4, totalAmount_);
    }
    if (couponAmount_ != 0L) {
      output.writeInt64(5, couponAmount_);
    }
    if (shippingAmount_ != 0L) {
      output.writeInt64(6, shippingAmount_);
    }
    if (payAmount_ != 0L) {
      output.writeInt64(7, payAmount_);
    }
    if (!getCommentBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 8, comment_);
    }
    for (int i = 0; i < skuData_.size(); i++) {
      output.writeMessage(9, skuData_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (userId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, userId_);
    }
    if (addressId_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, addressId_);
    }
    if (sourceType_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, sourceType_);
    }
    if (totalAmount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(4, totalAmount_);
    }
    if (couponAmount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(5, couponAmount_);
    }
    if (shippingAmount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(6, shippingAmount_);
    }
    if (payAmount_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(7, payAmount_);
    }
    if (!getCommentBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, comment_);
    }
    for (int i = 0; i < skuData_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(9, skuData_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.azure.csu.tiger.grpc.lib.CreateOrderRequest)) {
      return super.equals(obj);
    }
    com.azure.csu.tiger.grpc.lib.CreateOrderRequest other = (com.azure.csu.tiger.grpc.lib.CreateOrderRequest) obj;

    if (getUserId()
        != other.getUserId()) return false;
    if (getAddressId()
        != other.getAddressId()) return false;
    if (getSourceType()
        != other.getSourceType()) return false;
    if (getTotalAmount()
        != other.getTotalAmount()) return false;
    if (getCouponAmount()
        != other.getCouponAmount()) return false;
    if (getShippingAmount()
        != other.getShippingAmount()) return false;
    if (getPayAmount()
        != other.getPayAmount()) return false;
    if (!getComment()
        .equals(other.getComment())) return false;
    if (!getSkuDataList()
        .equals(other.getSkuDataList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + USERID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getUserId());
    hash = (37 * hash) + ADDRESSID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getAddressId());
    hash = (37 * hash) + SOURCETYPE_FIELD_NUMBER;
    hash = (53 * hash) + getSourceType();
    hash = (37 * hash) + TOTALAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTotalAmount());
    hash = (37 * hash) + COUPONAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getCouponAmount());
    hash = (37 * hash) + SHIPPINGAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getShippingAmount());
    hash = (37 * hash) + PAYAMOUNT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getPayAmount());
    hash = (37 * hash) + COMMENT_FIELD_NUMBER;
    hash = (53 * hash) + getComment().hashCode();
    if (getSkuDataCount() > 0) {
      hash = (37 * hash) + SKUDATA_FIELD_NUMBER;
      hash = (53 * hash) + getSkuDataList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.azure.csu.tiger.grpc.lib.CreateOrderRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.azure.csu.tiger.grpc.lib.CreateOrderRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.azure.csu.tiger.grpc.lib.CreateOrderRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.azure.csu.tiger.grpc.lib.CreateOrderRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.azure.csu.tiger.grpc.lib.CreateOrderRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.azure.csu.tiger.grpc.lib.CreateOrderRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.azure.csu.tiger.grpc.lib.CreateOrderRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.azure.csu.tiger.grpc.lib.CreateOrderRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.azure.csu.tiger.grpc.lib.CreateOrderRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.azure.csu.tiger.grpc.lib.CreateOrderRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.azure.csu.tiger.grpc.lib.CreateOrderRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.azure.csu.tiger.grpc.lib.CreateOrderRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.azure.csu.tiger.grpc.lib.CreateOrderRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code CreateOrderRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:CreateOrderRequest)
      com.azure.csu.tiger.grpc.lib.CreateOrderRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.azure.csu.tiger.grpc.lib.OrderProto.internal_static_CreateOrderRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.azure.csu.tiger.grpc.lib.OrderProto.internal_static_CreateOrderRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.azure.csu.tiger.grpc.lib.CreateOrderRequest.class, com.azure.csu.tiger.grpc.lib.CreateOrderRequest.Builder.class);
    }

    // Construct using com.azure.csu.tiger.grpc.lib.CreateOrderRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getSkuDataFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      userId_ = 0L;

      addressId_ = 0L;

      sourceType_ = 0;

      totalAmount_ = 0L;

      couponAmount_ = 0L;

      shippingAmount_ = 0L;

      payAmount_ = 0L;

      comment_ = "";

      if (skuDataBuilder_ == null) {
        skuData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        skuDataBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.azure.csu.tiger.grpc.lib.OrderProto.internal_static_CreateOrderRequest_descriptor;
    }

    @java.lang.Override
    public com.azure.csu.tiger.grpc.lib.CreateOrderRequest getDefaultInstanceForType() {
      return com.azure.csu.tiger.grpc.lib.CreateOrderRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.azure.csu.tiger.grpc.lib.CreateOrderRequest build() {
      com.azure.csu.tiger.grpc.lib.CreateOrderRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.azure.csu.tiger.grpc.lib.CreateOrderRequest buildPartial() {
      com.azure.csu.tiger.grpc.lib.CreateOrderRequest result = new com.azure.csu.tiger.grpc.lib.CreateOrderRequest(this);
      int from_bitField0_ = bitField0_;
      result.userId_ = userId_;
      result.addressId_ = addressId_;
      result.sourceType_ = sourceType_;
      result.totalAmount_ = totalAmount_;
      result.couponAmount_ = couponAmount_;
      result.shippingAmount_ = shippingAmount_;
      result.payAmount_ = payAmount_;
      result.comment_ = comment_;
      if (skuDataBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          skuData_ = java.util.Collections.unmodifiableList(skuData_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.skuData_ = skuData_;
      } else {
        result.skuData_ = skuDataBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.azure.csu.tiger.grpc.lib.CreateOrderRequest) {
        return mergeFrom((com.azure.csu.tiger.grpc.lib.CreateOrderRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.azure.csu.tiger.grpc.lib.CreateOrderRequest other) {
      if (other == com.azure.csu.tiger.grpc.lib.CreateOrderRequest.getDefaultInstance()) return this;
      if (other.getUserId() != 0L) {
        setUserId(other.getUserId());
      }
      if (other.getAddressId() != 0L) {
        setAddressId(other.getAddressId());
      }
      if (other.getSourceType() != 0) {
        setSourceType(other.getSourceType());
      }
      if (other.getTotalAmount() != 0L) {
        setTotalAmount(other.getTotalAmount());
      }
      if (other.getCouponAmount() != 0L) {
        setCouponAmount(other.getCouponAmount());
      }
      if (other.getShippingAmount() != 0L) {
        setShippingAmount(other.getShippingAmount());
      }
      if (other.getPayAmount() != 0L) {
        setPayAmount(other.getPayAmount());
      }
      if (!other.getComment().isEmpty()) {
        comment_ = other.comment_;
        onChanged();
      }
      if (skuDataBuilder_ == null) {
        if (!other.skuData_.isEmpty()) {
          if (skuData_.isEmpty()) {
            skuData_ = other.skuData_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureSkuDataIsMutable();
            skuData_.addAll(other.skuData_);
          }
          onChanged();
        }
      } else {
        if (!other.skuData_.isEmpty()) {
          if (skuDataBuilder_.isEmpty()) {
            skuDataBuilder_.dispose();
            skuDataBuilder_ = null;
            skuData_ = other.skuData_;
            bitField0_ = (bitField0_ & ~0x00000001);
            skuDataBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getSkuDataFieldBuilder() : null;
          } else {
            skuDataBuilder_.addAllMessages(other.skuData_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.azure.csu.tiger.grpc.lib.CreateOrderRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.azure.csu.tiger.grpc.lib.CreateOrderRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private long userId_ ;
    /**
     * <code>int64 userId = 1;</code>
     * @return The userId.
     */
    @java.lang.Override
    public long getUserId() {
      return userId_;
    }
    /**
     * <code>int64 userId = 1;</code>
     * @param value The userId to set.
     * @return This builder for chaining.
     */
    public Builder setUserId(long value) {
      
      userId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 userId = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearUserId() {
      
      userId_ = 0L;
      onChanged();
      return this;
    }

    private long addressId_ ;
    /**
     * <code>int64 addressId = 2;</code>
     * @return The addressId.
     */
    @java.lang.Override
    public long getAddressId() {
      return addressId_;
    }
    /**
     * <code>int64 addressId = 2;</code>
     * @param value The addressId to set.
     * @return This builder for chaining.
     */
    public Builder setAddressId(long value) {
      
      addressId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 addressId = 2;</code>
     * @return This builder for chaining.
     */
    public Builder clearAddressId() {
      
      addressId_ = 0L;
      onChanged();
      return this;
    }

    private int sourceType_ ;
    /**
     * <code>int32 sourceType = 3;</code>
     * @return The sourceType.
     */
    @java.lang.Override
    public int getSourceType() {
      return sourceType_;
    }
    /**
     * <code>int32 sourceType = 3;</code>
     * @param value The sourceType to set.
     * @return This builder for chaining.
     */
    public Builder setSourceType(int value) {
      
      sourceType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 sourceType = 3;</code>
     * @return This builder for chaining.
     */
    public Builder clearSourceType() {
      
      sourceType_ = 0;
      onChanged();
      return this;
    }

    private long totalAmount_ ;
    /**
     * <code>int64 totalAmount = 4;</code>
     * @return The totalAmount.
     */
    @java.lang.Override
    public long getTotalAmount() {
      return totalAmount_;
    }
    /**
     * <code>int64 totalAmount = 4;</code>
     * @param value The totalAmount to set.
     * @return This builder for chaining.
     */
    public Builder setTotalAmount(long value) {
      
      totalAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 totalAmount = 4;</code>
     * @return This builder for chaining.
     */
    public Builder clearTotalAmount() {
      
      totalAmount_ = 0L;
      onChanged();
      return this;
    }

    private long couponAmount_ ;
    /**
     * <code>int64 couponAmount = 5;</code>
     * @return The couponAmount.
     */
    @java.lang.Override
    public long getCouponAmount() {
      return couponAmount_;
    }
    /**
     * <code>int64 couponAmount = 5;</code>
     * @param value The couponAmount to set.
     * @return This builder for chaining.
     */
    public Builder setCouponAmount(long value) {
      
      couponAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 couponAmount = 5;</code>
     * @return This builder for chaining.
     */
    public Builder clearCouponAmount() {
      
      couponAmount_ = 0L;
      onChanged();
      return this;
    }

    private long shippingAmount_ ;
    /**
     * <code>int64 shippingAmount = 6;</code>
     * @return The shippingAmount.
     */
    @java.lang.Override
    public long getShippingAmount() {
      return shippingAmount_;
    }
    /**
     * <code>int64 shippingAmount = 6;</code>
     * @param value The shippingAmount to set.
     * @return This builder for chaining.
     */
    public Builder setShippingAmount(long value) {
      
      shippingAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 shippingAmount = 6;</code>
     * @return This builder for chaining.
     */
    public Builder clearShippingAmount() {
      
      shippingAmount_ = 0L;
      onChanged();
      return this;
    }

    private long payAmount_ ;
    /**
     * <code>int64 payAmount = 7;</code>
     * @return The payAmount.
     */
    @java.lang.Override
    public long getPayAmount() {
      return payAmount_;
    }
    /**
     * <code>int64 payAmount = 7;</code>
     * @param value The payAmount to set.
     * @return This builder for chaining.
     */
    public Builder setPayAmount(long value) {
      
      payAmount_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 payAmount = 7;</code>
     * @return This builder for chaining.
     */
    public Builder clearPayAmount() {
      
      payAmount_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object comment_ = "";
    /**
     * <code>string comment = 8;</code>
     * @return The comment.
     */
    public java.lang.String getComment() {
      java.lang.Object ref = comment_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comment_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string comment = 8;</code>
     * @return The bytes for comment.
     */
    public com.google.protobuf.ByteString
        getCommentBytes() {
      java.lang.Object ref = comment_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comment_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string comment = 8;</code>
     * @param value The comment to set.
     * @return This builder for chaining.
     */
    public Builder setComment(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      comment_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string comment = 8;</code>
     * @return This builder for chaining.
     */
    public Builder clearComment() {
      
      comment_ = getDefaultInstance().getComment();
      onChanged();
      return this;
    }
    /**
     * <code>string comment = 8;</code>
     * @param value The bytes for comment to set.
     * @return This builder for chaining.
     */
    public Builder setCommentBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      comment_ = value;
      onChanged();
      return this;
    }

    private java.util.List<com.azure.csu.tiger.grpc.lib.OrderItemSku> skuData_ =
      java.util.Collections.emptyList();
    private void ensureSkuDataIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        skuData_ = new java.util.ArrayList<com.azure.csu.tiger.grpc.lib.OrderItemSku>(skuData_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.azure.csu.tiger.grpc.lib.OrderItemSku, com.azure.csu.tiger.grpc.lib.OrderItemSku.Builder, com.azure.csu.tiger.grpc.lib.OrderItemSkuOrBuilder> skuDataBuilder_;

    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public java.util.List<com.azure.csu.tiger.grpc.lib.OrderItemSku> getSkuDataList() {
      if (skuDataBuilder_ == null) {
        return java.util.Collections.unmodifiableList(skuData_);
      } else {
        return skuDataBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public int getSkuDataCount() {
      if (skuDataBuilder_ == null) {
        return skuData_.size();
      } else {
        return skuDataBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public com.azure.csu.tiger.grpc.lib.OrderItemSku getSkuData(int index) {
      if (skuDataBuilder_ == null) {
        return skuData_.get(index);
      } else {
        return skuDataBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public Builder setSkuData(
        int index, com.azure.csu.tiger.grpc.lib.OrderItemSku value) {
      if (skuDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkuDataIsMutable();
        skuData_.set(index, value);
        onChanged();
      } else {
        skuDataBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public Builder setSkuData(
        int index, com.azure.csu.tiger.grpc.lib.OrderItemSku.Builder builderForValue) {
      if (skuDataBuilder_ == null) {
        ensureSkuDataIsMutable();
        skuData_.set(index, builderForValue.build());
        onChanged();
      } else {
        skuDataBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public Builder addSkuData(com.azure.csu.tiger.grpc.lib.OrderItemSku value) {
      if (skuDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkuDataIsMutable();
        skuData_.add(value);
        onChanged();
      } else {
        skuDataBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public Builder addSkuData(
        int index, com.azure.csu.tiger.grpc.lib.OrderItemSku value) {
      if (skuDataBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkuDataIsMutable();
        skuData_.add(index, value);
        onChanged();
      } else {
        skuDataBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public Builder addSkuData(
        com.azure.csu.tiger.grpc.lib.OrderItemSku.Builder builderForValue) {
      if (skuDataBuilder_ == null) {
        ensureSkuDataIsMutable();
        skuData_.add(builderForValue.build());
        onChanged();
      } else {
        skuDataBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public Builder addSkuData(
        int index, com.azure.csu.tiger.grpc.lib.OrderItemSku.Builder builderForValue) {
      if (skuDataBuilder_ == null) {
        ensureSkuDataIsMutable();
        skuData_.add(index, builderForValue.build());
        onChanged();
      } else {
        skuDataBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public Builder addAllSkuData(
        java.lang.Iterable<? extends com.azure.csu.tiger.grpc.lib.OrderItemSku> values) {
      if (skuDataBuilder_ == null) {
        ensureSkuDataIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, skuData_);
        onChanged();
      } else {
        skuDataBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public Builder clearSkuData() {
      if (skuDataBuilder_ == null) {
        skuData_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        skuDataBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public Builder removeSkuData(int index) {
      if (skuDataBuilder_ == null) {
        ensureSkuDataIsMutable();
        skuData_.remove(index);
        onChanged();
      } else {
        skuDataBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public com.azure.csu.tiger.grpc.lib.OrderItemSku.Builder getSkuDataBuilder(
        int index) {
      return getSkuDataFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public com.azure.csu.tiger.grpc.lib.OrderItemSkuOrBuilder getSkuDataOrBuilder(
        int index) {
      if (skuDataBuilder_ == null) {
        return skuData_.get(index);  } else {
        return skuDataBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public java.util.List<? extends com.azure.csu.tiger.grpc.lib.OrderItemSkuOrBuilder> 
         getSkuDataOrBuilderList() {
      if (skuDataBuilder_ != null) {
        return skuDataBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(skuData_);
      }
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public com.azure.csu.tiger.grpc.lib.OrderItemSku.Builder addSkuDataBuilder() {
      return getSkuDataFieldBuilder().addBuilder(
          com.azure.csu.tiger.grpc.lib.OrderItemSku.getDefaultInstance());
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public com.azure.csu.tiger.grpc.lib.OrderItemSku.Builder addSkuDataBuilder(
        int index) {
      return getSkuDataFieldBuilder().addBuilder(
          index, com.azure.csu.tiger.grpc.lib.OrderItemSku.getDefaultInstance());
    }
    /**
     * <code>repeated .OrderItemSku skuData = 9;</code>
     */
    public java.util.List<com.azure.csu.tiger.grpc.lib.OrderItemSku.Builder> 
         getSkuDataBuilderList() {
      return getSkuDataFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.azure.csu.tiger.grpc.lib.OrderItemSku, com.azure.csu.tiger.grpc.lib.OrderItemSku.Builder, com.azure.csu.tiger.grpc.lib.OrderItemSkuOrBuilder> 
        getSkuDataFieldBuilder() {
      if (skuDataBuilder_ == null) {
        skuDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.azure.csu.tiger.grpc.lib.OrderItemSku, com.azure.csu.tiger.grpc.lib.OrderItemSku.Builder, com.azure.csu.tiger.grpc.lib.OrderItemSkuOrBuilder>(
                skuData_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        skuData_ = null;
      }
      return skuDataBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:CreateOrderRequest)
  }

  // @@protoc_insertion_point(class_scope:CreateOrderRequest)
  private static final com.azure.csu.tiger.grpc.lib.CreateOrderRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.azure.csu.tiger.grpc.lib.CreateOrderRequest();
  }

  public static com.azure.csu.tiger.grpc.lib.CreateOrderRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateOrderRequest>
      PARSER = new com.google.protobuf.AbstractParser<CreateOrderRequest>() {
    @java.lang.Override
    public CreateOrderRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateOrderRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateOrderRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateOrderRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.azure.csu.tiger.grpc.lib.CreateOrderRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

