// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.azure.csu.tiger.grpc.lib;

public interface GetOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetOrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>.OrderInfo data = 3;</code>
   * @return Whether the data field is set.
   */
  boolean hasData();
  /**
   * <code>.OrderInfo data = 3;</code>
   * @return The data.
   */
  com.azure.csu.tiger.grpc.lib.OrderInfo getData();
  /**
   * <code>.OrderInfo data = 3;</code>
   */
  com.azure.csu.tiger.grpc.lib.OrderInfoOrBuilder getDataOrBuilder();
}
