// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.azure.csu.tiger.grpc.lib;

public interface GetSkuDetailRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GetSkuDetailRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 skuId = 1;</code>
   * @return The skuId.
   */
  long getSkuId();
}
