// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.azure.csu.tiger.grpc.lib;

public interface ListOrderResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListOrderResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>repeated .OrderInfo data = 3;</code>
   */
  java.util.List<com.azure.csu.tiger.grpc.lib.OrderInfo> 
      getDataList();
  /**
   * <code>repeated .OrderInfo data = 3;</code>
   */
  com.azure.csu.tiger.grpc.lib.OrderInfo getData(int index);
  /**
   * <code>repeated .OrderInfo data = 3;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .OrderInfo data = 3;</code>
   */
  java.util.List<? extends com.azure.csu.tiger.grpc.lib.OrderInfoOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .OrderInfo data = 3;</code>
   */
  com.azure.csu.tiger.grpc.lib.OrderInfoOrBuilder getDataOrBuilder(
      int index);
}
