// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.azure.csu.tiger.grpc.lib;

public interface ListSkuRequest2OrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListSkuRequest2)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 categoryId = 3;</code>
   * @return The categoryId.
   */
  long getCategoryId();

  /**
   * <code>int32 offset = 4;</code>
   * @return The offset.
   */
  int getOffset();

  /**
   * <code>int32 limit = 5;</code>
   * @return The limit.
   */
  int getLimit();
}
