// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.azure.csu.tiger.grpc.lib;

public interface ListCartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListCartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>repeated .CartItem datas = 3;</code>
   */
  java.util.List<com.azure.csu.tiger.grpc.lib.CartItem> 
      getDatasList();
  /**
   * <code>repeated .CartItem datas = 3;</code>
   */
  com.azure.csu.tiger.grpc.lib.CartItem getDatas(int index);
  /**
   * <code>repeated .CartItem datas = 3;</code>
   */
  int getDatasCount();
  /**
   * <code>repeated .CartItem datas = 3;</code>
   */
  java.util.List<? extends com.azure.csu.tiger.grpc.lib.CartItemOrBuilder> 
      getDatasOrBuilderList();
  /**
   * <code>repeated .CartItem datas = 3;</code>
   */
  com.azure.csu.tiger.grpc.lib.CartItemOrBuilder getDatasOrBuilder(
      int index);
}
