// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.azure.csu.tiger.grpc.lib;

public interface ListOrderRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListOrderRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 orderId = 1;</code>
   * @return The orderId.
   */
  long getOrderId();
}
