// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.azure.csu.tiger.grpc.lib;

public interface ListSkuInfoResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:ListSkuInfoResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 code = 1;</code>
   * @return The code.
   */
  int getCode();

  /**
   * <code>bool success = 2;</code>
   * @return The success.
   */
  boolean getSuccess();

  /**
   * <code>repeated .SkuInfo datas = 3;</code>
   */
  java.util.List<com.azure.csu.tiger.grpc.lib.SkuInfo> 
      getDatasList();
  /**
   * <code>repeated .SkuInfo datas = 3;</code>
   */
  com.azure.csu.tiger.grpc.lib.SkuInfo getDatas(int index);
  /**
   * <code>repeated .SkuInfo datas = 3;</code>
   */
  int getDatasCount();
  /**
   * <code>repeated .SkuInfo datas = 3;</code>
   */
  java.util.List<? extends com.azure.csu.tiger.grpc.lib.SkuInfoOrBuilder> 
      getDatasOrBuilderList();
  /**
   * <code>repeated .SkuInfo datas = 3;</code>
   */
  com.azure.csu.tiger.grpc.lib.SkuInfoOrBuilder getDatasOrBuilder(
      int index);
}
