// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: order.proto

package com.azure.csu.tiger.grpc.lib;

public final class OrderProto {
  private OrderProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CreateOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CreateOrderResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListOrderRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListOrderRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListOrderResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListOrderResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013order.proto\032\nbase.proto\"\322\001\n\022CreateOrde" +
      "rRequest\022\016\n\006userId\030\001 \001(\003\022\021\n\taddressId\030\002 " +
      "\001(\003\022\022\n\nsourceType\030\003 \001(\005\022\023\n\013totalAmount\030\004" +
      " \001(\003\022\024\n\014couponAmount\030\005 \001(\003\022\026\n\016shippingAm" +
      "ount\030\006 \001(\003\022\021\n\tpayAmount\030\007 \001(\003\022\017\n\007comment" +
      "\030\010 \001(\t\022\036\n\007skuData\030\t \003(\0132\r.OrderItemSku\"4" +
      "\n\023CreateOrderResponse\022\014\n\004code\030\001 \001(\005\022\017\n\007s" +
      "uccess\030\002 \001(\010\"#\n\020ListOrderRequest\022\017\n\007orde" +
      "rId\030\001 \001(\003\"L\n\021ListOrderResponse\022\014\n\004code\030\001" +
      " \001(\005\022\017\n\007success\030\002 \001(\010\022\030\n\004data\030\003 \003(\0132\n.Or" +
      "derInfo2y\n\005Order\022:\n\013createOrder\022\023.Create" +
      "OrderRequest\032\024.CreateOrderResponse\"\000\0224\n\t" +
      "listOrder\022\021.ListOrderRequest\032\022.ListOrder" +
      "Response\"\000B,\n\034com.azure.csu.tiger.grpc.l" +
      "ibB\nOrderProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.azure.csu.tiger.grpc.lib.BaseProto.getDescriptor(),
        });
    internal_static_CreateOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CreateOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateOrderRequest_descriptor,
        new java.lang.String[] { "UserId", "AddressId", "SourceType", "TotalAmount", "CouponAmount", "ShippingAmount", "PayAmount", "Comment", "SkuData", });
    internal_static_CreateOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CreateOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CreateOrderResponse_descriptor,
        new java.lang.String[] { "Code", "Success", });
    internal_static_ListOrderRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ListOrderRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListOrderRequest_descriptor,
        new java.lang.String[] { "OrderId", });
    internal_static_ListOrderResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ListOrderResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListOrderResponse_descriptor,
        new java.lang.String[] { "Code", "Success", "Data", });
    com.azure.csu.tiger.grpc.lib.BaseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
