// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.azure.csu.tiger.grpc.lib;

public final class ProductProto {
  private ProductProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindCategoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindCategoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Category_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Category_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CategoryListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CategoryListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\"5\n\023FindCategoryRequest\022\014" +
      "\n\004name\030\001 \001(\t\022\020\n\010parentId\030\002 \001(\003\"T\n\010Catego" +
      "ry\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t\022\020\n\010parentId" +
      "\030\003 \001(\003\022\016\n\006isLeaf\030\004 \001(\010\022\014\n\004sort\030\005 \001(\005\"0\n\024" +
      "CategoryListResponse\022\030\n\005datas\030\001 \003(\0132\t.Ca" +
      "tegory2H\n\007Product\022=\n\014listCategory\022\024.Find" +
      "CategoryRequest\032\025.CategoryListResponse\"\000" +
      "B.\n\034com.azure.csu.tiger.grpc.libB\014Produc" +
      "tProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_FindCategoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FindCategoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindCategoryRequest_descriptor,
        new java.lang.String[] { "Name", "ParentId", });
    internal_static_Category_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Category_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Category_descriptor,
        new java.lang.String[] { "Id", "Name", "ParentId", "IsLeaf", "Sort", });
    internal_static_CategoryListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CategoryListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CategoryListResponse_descriptor,
        new java.lang.String[] { "Datas", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
