// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package com.azure.csu.tiger.grpc.lib;

public final class ProductProto {
  private ProductProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FindCategoryRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FindCategoryRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Category_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Category_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CategoryListResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CategoryListResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListSkuRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListSkuRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListSkuRequest2_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListSkuRequest2_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListSkuInfoResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListSkuInfoResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetSkuDetailRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetSkuDetailRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GetSkuDetailResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GetSkuDetailResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\032\nbase.proto\"5\n\023FindCateg" +
      "oryRequest\022\014\n\004name\030\001 \001(\t\022\020\n\010parentId\030\002 \001" +
      "(\003\"T\n\010Category\022\n\n\002id\030\001 \001(\003\022\014\n\004name\030\002 \001(\t" +
      "\022\020\n\010parentId\030\003 \001(\003\022\016\n\006isLeaf\030\004 \001(\010\022\014\n\004so" +
      "rt\030\005 \001(\005\"0\n\024CategoryListResponse\022\030\n\005data" +
      "s\030\001 \003(\0132\t.Category\"\037\n\016ListSkuRequest\022\r\n\005" +
      "skuId\030\001 \003(\003\"R\n\017ListSkuRequest2\022\014\n\004name\030\002" +
      " \001(\t\022\022\n\ncategoryId\030\003 \001(\003\022\016\n\006offset\030\004 \001(\005" +
      "\022\r\n\005limit\030\005 \001(\005\"M\n\023ListSkuInfoResponse\022\014" +
      "\n\004code\030\001 \001(\005\022\017\n\007success\030\002 \001(\010\022\027\n\005datas\030\003" +
      " \003(\0132\010.SkuInfo\"$\n\023GetSkuDetailRequest\022\r\n" +
      "\005skuId\030\001 \001(\003\"S\n\024GetSkuDetailResponse\022\014\n\004" +
      "code\030\001 \001(\005\022\017\n\007success\030\002 \001(\010\022\034\n\004data\030\003 \001(" +
      "\0132\016.SkuDetailInfo2\372\001\n\007Product\022=\n\014listCat" +
      "egory\022\024.FindCategoryRequest\032\025.CategoryLi" +
      "stResponse\"\000\0226\n\013listSkuInfo\022\017.ListSkuReq" +
      "uest\032\024.ListSkuInfoResponse\"\000\0225\n\tsearchSk" +
      "u\022\020.ListSkuRequest2\032\024.ListSkuInfoRespons" +
      "e\"\000\022A\n\020getSkuDetailInfo\022\024.GetSkuDetailRe" +
      "quest\032\025.GetSkuDetailResponse\"\000B.\n\034com.az" +
      "ure.csu.tiger.grpc.libB\014ProductProtoP\001b\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.azure.csu.tiger.grpc.lib.BaseProto.getDescriptor(),
        });
    internal_static_FindCategoryRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FindCategoryRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FindCategoryRequest_descriptor,
        new java.lang.String[] { "Name", "ParentId", });
    internal_static_Category_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Category_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Category_descriptor,
        new java.lang.String[] { "Id", "Name", "ParentId", "IsLeaf", "Sort", });
    internal_static_CategoryListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_CategoryListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CategoryListResponse_descriptor,
        new java.lang.String[] { "Datas", });
    internal_static_ListSkuRequest_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ListSkuRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListSkuRequest_descriptor,
        new java.lang.String[] { "SkuId", });
    internal_static_ListSkuRequest2_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ListSkuRequest2_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListSkuRequest2_descriptor,
        new java.lang.String[] { "Name", "CategoryId", "Offset", "Limit", });
    internal_static_ListSkuInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ListSkuInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListSkuInfoResponse_descriptor,
        new java.lang.String[] { "Code", "Success", "Datas", });
    internal_static_GetSkuDetailRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_GetSkuDetailRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetSkuDetailRequest_descriptor,
        new java.lang.String[] { "SkuId", });
    internal_static_GetSkuDetailResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_GetSkuDetailResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GetSkuDetailResponse_descriptor,
        new java.lang.String[] { "Code", "Success", "Data", });
    com.azure.csu.tiger.grpc.lib.BaseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
