// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: base.proto

package com.azure.csu.tiger.grpc.lib;

public interface SkuInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:SkuInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 skuId = 1;</code>
   * @return The skuId.
   */
  long getSkuId();

  /**
   * <code>int64 spuId = 2;</code>
   * @return The spuId.
   */
  long getSpuId();

  /**
   * <code>string name = 3;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 3;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int64 categoryId = 4;</code>
   * @return The categoryId.
   */
  long getCategoryId();

  /**
   * <code>int64 price = 5;</code>
   * @return The price.
   */
  long getPrice();

  /**
   * <code>int64 stock = 6;</code>
   * @return The stock.
   */
  long getStock();

  /**
   * <code>map&lt;string, string&gt; attr = 7;</code>
   */
  int getAttrCount();
  /**
   * <code>map&lt;string, string&gt; attr = 7;</code>
   */
  boolean containsAttr(
      java.lang.String key);
  /**
   * Use {@link #getAttrMap()} instead.
   */
  @java.lang.Deprecated
  java.util.Map<java.lang.String, java.lang.String>
  getAttr();
  /**
   * <code>map&lt;string, string&gt; attr = 7;</code>
   */
  java.util.Map<java.lang.String, java.lang.String>
  getAttrMap();
  /**
   * <code>map&lt;string, string&gt; attr = 7;</code>
   */

  java.lang.String getAttrOrDefault(
      java.lang.String key,
      java.lang.String defaultValue);
  /**
   * <code>map&lt;string, string&gt; attr = 7;</code>
   */

  java.lang.String getAttrOrThrow(
      java.lang.String key);
}
