// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.azure.csu.tiger.grpc.lib;

public final class UserProto {
  private UserProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddCartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddCartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_AddCartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_AddCartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListCartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListCartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ListCartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ListCartResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClearCartRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClearCartRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ClearCartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ClearCartResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\032\nbase.proto\"G\n\016AddCartReque" +
      "st\022\013\n\003uid\030\001 \001(\003\022\r\n\005skuId\030\002 \001(\003\022\031\n\007skuInf" +
      "o\030\003 \001(\0132\010.SkuInfo\"0\n\017AddCartResponse\022\014\n\004" +
      "code\030\001 \001(\005\022\017\n\007success\030\002 \001(\010\"\036\n\017ListCartR" +
      "equest\022\013\n\003uid\030\001 \001(\003\"K\n\020ListCartResponse\022" +
      "\014\n\004code\030\001 \001(\005\022\017\n\007success\030\002 \001(\010\022\030\n\005datas\030" +
      "\003 \003(\0132\t.CartItem\"\037\n\020ClearCartRequest\022\013\n\003" +
      "uid\030\001 \001(\003\"2\n\021ClearCartResponse\022\014\n\004code\030\001" +
      " \001(\005\022\017\n\007success\030\002 \001(\0102\237\001\n\004User\022.\n\007addCar" +
      "t\022\017.AddCartRequest\032\020.AddCartResponse\"\000\0221" +
      "\n\010listCart\022\020.ListCartRequest\032\021.ListCartR" +
      "esponse\"\000\0224\n\tclearCart\022\021.ClearCartReques" +
      "t\032\022.ClearCartResponse\"\000B+\n\034com.azure.csu" +
      ".tiger.grpc.libB\tUserProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.azure.csu.tiger.grpc.lib.BaseProto.getDescriptor(),
        });
    internal_static_AddCartRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_AddCartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddCartRequest_descriptor,
        new java.lang.String[] { "Uid", "SkuId", "SkuInfo", });
    internal_static_AddCartResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_AddCartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_AddCartResponse_descriptor,
        new java.lang.String[] { "Code", "Success", });
    internal_static_ListCartRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_ListCartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListCartRequest_descriptor,
        new java.lang.String[] { "Uid", });
    internal_static_ListCartResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_ListCartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ListCartResponse_descriptor,
        new java.lang.String[] { "Code", "Success", "Datas", });
    internal_static_ClearCartRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_ClearCartRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClearCartRequest_descriptor,
        new java.lang.String[] { "Uid", });
    internal_static_ClearCartResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_ClearCartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ClearCartResponse_descriptor,
        new java.lang.String[] { "Code", "Success", });
    com.azure.csu.tiger.grpc.lib.BaseProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
