spring:
  redis:
    database: 0
    #    host: 20.252.202.28
    #    password: 4L62C7zQZg
    #    port: 7777
    host: sheintest.redis.cache.windows.net
    port: 6379
    password: DFALHzmo7mAkMYxTCrrOqwuepRKLYIEhIAzCaAzmkg4=
    jedis:
      pool:
        enable: true
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1
    connect-timeout: 30000
  zipkin:
    base-url: http://20.171.143.16:9411/
    sender:
      type: web #使用http的方式传输数据
    sleuth:
      sampler:
        probability: 1 # 将采样比例设置为 1.0，也就是全部都需要。默认是0.1也就是10%，一般情况下，10%就够用了
  main:
   allow-circular-references: true
grpc:
  client:
    emall-order:
      address: 'discovery:///emall-order'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    emall-product:
      address: 'discovery:///emall-product'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
#logging:
#  level:
#    root: debug
