spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  redis:
    database: 0
    host: 10.1.0.70
    port: 7617
    password: 4L62C7zQZg
    jedis:
      pool:
        enable: true
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1
    connect-timeout: 30000
  zipkin:
    base-url: http://20.2.136.248:9411/
    sender:
      type: web #使用http的方式传输数据
    sleuth:
      web:
        skip-pattern: ^(?!/emall).*
      sampler:
        probability: 1 # 将采样比例设置为 1.0，也就是全部都需要。默认是0.1也就是10%，一般情况下，10%就够用了
  main:
   allow-circular-references: true
grpc:
  client:
    emall-order:
      address: 'discovery:///emall-order'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    emall-product:
      address: 'discovery:///emall-product'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
    emall-user:
      address: 'discovery:///emall-user'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
swagger:
  enabled: true
#logging:
#  level:
#    root: debug
