/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.product.jooq;


import com.azure.csu.tiger.product.jooq.tables.Attribute;
import com.azure.csu.tiger.product.jooq.tables.AttributeCategory;
import com.azure.csu.tiger.product.jooq.tables.AttributeEnum;
import com.azure.csu.tiger.product.jooq.tables.AttributeValue;
import com.azure.csu.tiger.product.jooq.tables.Brand;
import com.azure.csu.tiger.product.jooq.tables.Category;
import com.azure.csu.tiger.product.jooq.tables.CategoryBrand;
import com.azure.csu.tiger.product.jooq.tables.Coupon;
import com.azure.csu.tiger.product.jooq.tables.CouponRange;
import com.azure.csu.tiger.product.jooq.tables.CouponTaken;
import com.azure.csu.tiger.product.jooq.tables.CouponUsed;
import com.azure.csu.tiger.product.jooq.tables.Sku;
import com.azure.csu.tiger.product.jooq.tables.SkuComment;
import com.azure.csu.tiger.product.jooq.tables.SkuImage;
import com.azure.csu.tiger.product.jooq.tables.Spu;
import com.azure.csu.tiger.product.jooq.tables.records.AttributeCategoryRecord;
import com.azure.csu.tiger.product.jooq.tables.records.AttributeEnumRecord;
import com.azure.csu.tiger.product.jooq.tables.records.AttributeRecord;
import com.azure.csu.tiger.product.jooq.tables.records.AttributeValueRecord;
import com.azure.csu.tiger.product.jooq.tables.records.BrandRecord;
import com.azure.csu.tiger.product.jooq.tables.records.CategoryBrandRecord;
import com.azure.csu.tiger.product.jooq.tables.records.CategoryRecord;
import com.azure.csu.tiger.product.jooq.tables.records.CouponRangeRecord;
import com.azure.csu.tiger.product.jooq.tables.records.CouponRecord;
import com.azure.csu.tiger.product.jooq.tables.records.CouponTakenRecord;
import com.azure.csu.tiger.product.jooq.tables.records.CouponUsedRecord;
import com.azure.csu.tiger.product.jooq.tables.records.SkuCommentRecord;
import com.azure.csu.tiger.product.jooq.tables.records.SkuImageRecord;
import com.azure.csu.tiger.product.jooq.tables.records.SkuRecord;
import com.azure.csu.tiger.product.jooq.tables.records.SpuRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in 
 * product_center.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<AttributeRecord> KEY_ATTRIBUTE_PRIMARY = Internal.createUniqueKey(Attribute.ATTRIBUTE, DSL.name("KEY_attribute_PRIMARY"), new TableField[] { Attribute.ATTRIBUTE.ID }, true);
    public static final UniqueKey<AttributeCategoryRecord> KEY_ATTRIBUTE_CATEGORY_PRIMARY = Internal.createUniqueKey(AttributeCategory.ATTRIBUTE_CATEGORY, DSL.name("KEY_attribute_category_PRIMARY"), new TableField[] { AttributeCategory.ATTRIBUTE_CATEGORY.ID }, true);
    public static final UniqueKey<AttributeEnumRecord> KEY_ATTRIBUTE_ENUM_PRIMARY = Internal.createUniqueKey(AttributeEnum.ATTRIBUTE_ENUM, DSL.name("KEY_attribute_enum_PRIMARY"), new TableField[] { AttributeEnum.ATTRIBUTE_ENUM.ID }, true);
    public static final UniqueKey<AttributeValueRecord> KEY_ATTRIBUTE_VALUE_PRIMARY = Internal.createUniqueKey(AttributeValue.ATTRIBUTE_VALUE, DSL.name("KEY_attribute_value_PRIMARY"), new TableField[] { AttributeValue.ATTRIBUTE_VALUE.ID }, true);
    public static final UniqueKey<BrandRecord> KEY_BRAND_PRIMARY = Internal.createUniqueKey(Brand.BRAND, DSL.name("KEY_brand_PRIMARY"), new TableField[] { Brand.BRAND.ID }, true);
    public static final UniqueKey<CategoryRecord> KEY_CATEGORY_PRIMARY = Internal.createUniqueKey(Category.CATEGORY, DSL.name("KEY_category_PRIMARY"), new TableField[] { Category.CATEGORY.ID }, true);
    public static final UniqueKey<CategoryBrandRecord> KEY_CATEGORY_BRAND_PRIMARY = Internal.createUniqueKey(CategoryBrand.CATEGORY_BRAND, DSL.name("KEY_category_brand_PRIMARY"), new TableField[] { CategoryBrand.CATEGORY_BRAND.ID }, true);
    public static final UniqueKey<CouponRecord> KEY_COUPON_PRIMARY = Internal.createUniqueKey(Coupon.COUPON, DSL.name("KEY_coupon_PRIMARY"), new TableField[] { Coupon.COUPON.ID }, true);
    public static final UniqueKey<CouponRangeRecord> KEY_COUPON_RANGE_PRIMARY = Internal.createUniqueKey(CouponRange.COUPON_RANGE, DSL.name("KEY_coupon_range_PRIMARY"), new TableField[] { CouponRange.COUPON_RANGE.ID }, true);
    public static final UniqueKey<CouponTakenRecord> KEY_COUPON_TAKEN_PRIMARY = Internal.createUniqueKey(CouponTaken.COUPON_TAKEN, DSL.name("KEY_coupon_taken_PRIMARY"), new TableField[] { CouponTaken.COUPON_TAKEN.ID }, true);
    public static final UniqueKey<CouponUsedRecord> KEY_COUPON_USED_PRIMARY = Internal.createUniqueKey(CouponUsed.COUPON_USED, DSL.name("KEY_coupon_used_PRIMARY"), new TableField[] { CouponUsed.COUPON_USED.ID }, true);
    public static final UniqueKey<SkuRecord> KEY_SKU_PRIMARY = Internal.createUniqueKey(Sku.SKU, DSL.name("KEY_sku_PRIMARY"), new TableField[] { Sku.SKU.ID }, true);
    public static final UniqueKey<SkuCommentRecord> KEY_SKU_COMMENT_PRIMARY = Internal.createUniqueKey(SkuComment.SKU_COMMENT, DSL.name("KEY_sku_comment_PRIMARY"), new TableField[] { SkuComment.SKU_COMMENT.ID }, true);
    public static final UniqueKey<SkuImageRecord> KEY_SKU_IMAGE_PRIMARY = Internal.createUniqueKey(SkuImage.SKU_IMAGE, DSL.name("KEY_sku_image_PRIMARY"), new TableField[] { SkuImage.SKU_IMAGE.ID }, true);
    public static final UniqueKey<SpuRecord> KEY_SPU_PRIMARY = Internal.createUniqueKey(Spu.SPU, DSL.name("KEY_spu_PRIMARY"), new TableField[] { Spu.SPU.ID }, true);
}
