/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.user.jooq.tables.records;


import com.azure.csu.tiger.user.jooq.tables.CartDetail;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 购物车详情表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CartDetailRecord extends UpdatableRecordImpl<CartDetailRecord> implements Record6<Long, Long, Long, Long, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user_center.cart_detail.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>user_center.cart_detail.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>user_center.cart_detail.user_id</code>. 用户id
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>user_center.cart_detail.user_id</code>. 用户id
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>user_center.cart_detail.sku_id</code>. SKU id
     */
    public void setSkuId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>user_center.cart_detail.sku_id</code>. SKU id
     */
    public Long getSkuId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>user_center.cart_detail.sku_num</code>. 数量
     */
    public void setSkuNum(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>user_center.cart_detail.sku_num</code>. 数量
     */
    public Long getSkuNum() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>user_center.cart_detail.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>user_center.cart_detail.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>user_center.cart_detail.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>user_center.cart_detail.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, Long, Long, Long, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, Long, Long, Long, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return CartDetail.CART_DETAIL.ID;
    }

    @Override
    public Field<Long> field2() {
        return CartDetail.CART_DETAIL.USER_ID;
    }

    @Override
    public Field<Long> field3() {
        return CartDetail.CART_DETAIL.SKU_ID;
    }

    @Override
    public Field<Long> field4() {
        return CartDetail.CART_DETAIL.SKU_NUM;
    }

    @Override
    public Field<LocalDateTime> field5() {
        return CartDetail.CART_DETAIL.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field6() {
        return CartDetail.CART_DETAIL.MODIFY_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public Long component3() {
        return getSkuId();
    }

    @Override
    public Long component4() {
        return getSkuNum();
    }

    @Override
    public LocalDateTime component5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component6() {
        return getModifyTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public Long value3() {
        return getSkuId();
    }

    @Override
    public Long value4() {
        return getSkuNum();
    }

    @Override
    public LocalDateTime value5() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value6() {
        return getModifyTime();
    }

    @Override
    public CartDetailRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public CartDetailRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public CartDetailRecord value3(Long value) {
        setSkuId(value);
        return this;
    }

    @Override
    public CartDetailRecord value4(Long value) {
        setSkuNum(value);
        return this;
    }

    @Override
    public CartDetailRecord value5(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public CartDetailRecord value6(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public CartDetailRecord values(Long value1, Long value2, Long value3, Long value4, LocalDateTime value5, LocalDateTime value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CartDetailRecord
     */
    public CartDetailRecord() {
        super(CartDetail.CART_DETAIL);
    }

    /**
     * Create a detached, initialised CartDetailRecord
     */
    public CartDetailRecord(Long id, Long userId, Long skuId, Long skuNum, LocalDateTime createTime, LocalDateTime modifyTime) {
        super(CartDetail.CART_DETAIL);

        setId(id);
        setUserId(userId);
        setSkuId(skuId);
        setSkuNum(skuNum);
        setCreateTime(createTime);
        setModifyTime(modifyTime);
    }
}
