/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.user.jooq.tables.records;


import com.azure.csu.tiger.user.jooq.tables.UserAddress;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户地址表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserAddressRecord extends UpdatableRecordImpl<UserAddressRecord> implements Record13<Long, Long, String, String, String, String, String, String, Byte, LocalDateTime, LocalDateTime, Long, Long> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user_center.user_address.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>user_center.user_address.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>user_center.user_address.user_id</code>. 用户id
     */
    public void setUserId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>user_center.user_address.user_id</code>. 用户id
     */
    public Long getUserId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>user_center.user_address.name</code>. 联系人姓名
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user_center.user_address.name</code>. 联系人姓名
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user_center.user_address.phone_number</code>. 联系人手机号
     */
    public void setPhoneNumber(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user_center.user_address.phone_number</code>. 联系人手机号
     */
    public String getPhoneNumber() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user_center.user_address.province</code>. 省
     */
    public void setProvince(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>user_center.user_address.province</code>. 省
     */
    public String getProvince() {
        return (String) get(4);
    }

    /**
     * Setter for <code>user_center.user_address.city</code>. 市
     */
    public void setCity(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>user_center.user_address.city</code>. 市
     */
    public String getCity() {
        return (String) get(5);
    }

    /**
     * Setter for <code>user_center.user_address.region</code>. 区
     */
    public void setRegion(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>user_center.user_address.region</code>. 区
     */
    public String getRegion() {
        return (String) get(6);
    }

    /**
     * Setter for <code>user_center.user_address.detail_address</code>. 详细地址
     */
    public void setDetailAddress(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>user_center.user_address.detail_address</code>. 详细地址
     */
    public String getDetailAddress() {
        return (String) get(7);
    }

    /**
     * Setter for <code>user_center.user_address.is_default</code>. 是否默认地址 0-否，1-是
     */
    public void setIsDefault(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>user_center.user_address.is_default</code>. 是否默认地址 0-否，1-是
     */
    public Byte getIsDefault() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>user_center.user_address.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>user_center.user_address.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>user_center.user_address.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>user_center.user_address.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>user_center.user_address.create_user_id</code>.
     */
    public void setCreateUserId(Long value) {
        set(11, value);
    }

    /**
     * Getter for <code>user_center.user_address.create_user_id</code>.
     */
    public Long getCreateUserId() {
        return (Long) get(11);
    }

    /**
     * Setter for <code>user_center.user_address.modify_user_id</code>.
     */
    public void setModifyUserId(Long value) {
        set(12, value);
    }

    /**
     * Getter for <code>user_center.user_address.modify_user_id</code>.
     */
    public Long getModifyUserId() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row13<Long, Long, String, String, String, String, String, String, Byte, LocalDateTime, LocalDateTime, Long, Long> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    @Override
    public Row13<Long, Long, String, String, String, String, String, String, Byte, LocalDateTime, LocalDateTime, Long, Long> valuesRow() {
        return (Row13) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return UserAddress.USER_ADDRESS.ID;
    }

    @Override
    public Field<Long> field2() {
        return UserAddress.USER_ADDRESS.USER_ID;
    }

    @Override
    public Field<String> field3() {
        return UserAddress.USER_ADDRESS.NAME;
    }

    @Override
    public Field<String> field4() {
        return UserAddress.USER_ADDRESS.PHONE_NUMBER;
    }

    @Override
    public Field<String> field5() {
        return UserAddress.USER_ADDRESS.PROVINCE;
    }

    @Override
    public Field<String> field6() {
        return UserAddress.USER_ADDRESS.CITY;
    }

    @Override
    public Field<String> field7() {
        return UserAddress.USER_ADDRESS.REGION;
    }

    @Override
    public Field<String> field8() {
        return UserAddress.USER_ADDRESS.DETAIL_ADDRESS;
    }

    @Override
    public Field<Byte> field9() {
        return UserAddress.USER_ADDRESS.IS_DEFAULT;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return UserAddress.USER_ADDRESS.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return UserAddress.USER_ADDRESS.MODIFY_TIME;
    }

    @Override
    public Field<Long> field12() {
        return UserAddress.USER_ADDRESS.CREATE_USER_ID;
    }

    @Override
    public Field<Long> field13() {
        return UserAddress.USER_ADDRESS.MODIFY_USER_ID;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public Long component2() {
        return getUserId();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getPhoneNumber();
    }

    @Override
    public String component5() {
        return getProvince();
    }

    @Override
    public String component6() {
        return getCity();
    }

    @Override
    public String component7() {
        return getRegion();
    }

    @Override
    public String component8() {
        return getDetailAddress();
    }

    @Override
    public Byte component9() {
        return getIsDefault();
    }

    @Override
    public LocalDateTime component10() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component11() {
        return getModifyTime();
    }

    @Override
    public Long component12() {
        return getCreateUserId();
    }

    @Override
    public Long component13() {
        return getModifyUserId();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public Long value2() {
        return getUserId();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getPhoneNumber();
    }

    @Override
    public String value5() {
        return getProvince();
    }

    @Override
    public String value6() {
        return getCity();
    }

    @Override
    public String value7() {
        return getRegion();
    }

    @Override
    public String value8() {
        return getDetailAddress();
    }

    @Override
    public Byte value9() {
        return getIsDefault();
    }

    @Override
    public LocalDateTime value10() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value11() {
        return getModifyTime();
    }

    @Override
    public Long value12() {
        return getCreateUserId();
    }

    @Override
    public Long value13() {
        return getModifyUserId();
    }

    @Override
    public UserAddressRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserAddressRecord value2(Long value) {
        setUserId(value);
        return this;
    }

    @Override
    public UserAddressRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public UserAddressRecord value4(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public UserAddressRecord value5(String value) {
        setProvince(value);
        return this;
    }

    @Override
    public UserAddressRecord value6(String value) {
        setCity(value);
        return this;
    }

    @Override
    public UserAddressRecord value7(String value) {
        setRegion(value);
        return this;
    }

    @Override
    public UserAddressRecord value8(String value) {
        setDetailAddress(value);
        return this;
    }

    @Override
    public UserAddressRecord value9(Byte value) {
        setIsDefault(value);
        return this;
    }

    @Override
    public UserAddressRecord value10(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public UserAddressRecord value11(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public UserAddressRecord value12(Long value) {
        setCreateUserId(value);
        return this;
    }

    @Override
    public UserAddressRecord value13(Long value) {
        setModifyUserId(value);
        return this;
    }

    @Override
    public UserAddressRecord values(Long value1, Long value2, String value3, String value4, String value5, String value6, String value7, String value8, Byte value9, LocalDateTime value10, LocalDateTime value11, Long value12, Long value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserAddressRecord
     */
    public UserAddressRecord() {
        super(UserAddress.USER_ADDRESS);
    }

    /**
     * Create a detached, initialised UserAddressRecord
     */
    public UserAddressRecord(Long id, Long userId, String name, String phoneNumber, String province, String city, String region, String detailAddress, Byte isDefault, LocalDateTime createTime, LocalDateTime modifyTime, Long createUserId, Long modifyUserId) {
        super(UserAddress.USER_ADDRESS);

        setId(id);
        setUserId(userId);
        setName(name);
        setPhoneNumber(phoneNumber);
        setProvince(province);
        setCity(city);
        setRegion(region);
        setDetailAddress(detailAddress);
        setIsDefault(isDefault);
        setCreateTime(createTime);
        setModifyTime(modifyTime);
        setCreateUserId(createUserId);
        setModifyUserId(modifyUserId);
    }
}
