/*
 * This file is generated by jOOQ.
 */
package com.azure.csu.tiger.user.jooq.tables.records;


import com.azure.csu.tiger.user.jooq.tables.User;

import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * 用户表
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends UpdatableRecordImpl<UserRecord> implements Record11<Long, String, String, String, String, String, String, Byte, Byte, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>user_center.user.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>user_center.user.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>user_center.user.login_name</code>. 用户名称
     */
    public void setLoginName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>user_center.user.login_name</code>. 用户名称
     */
    public String getLoginName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>user_center.user.nick_name</code>. 昵称
     */
    public void setNickName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>user_center.user.nick_name</code>. 昵称
     */
    public String getNickName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>user_center.user.password</code>. 密码, 测试用途明文存储
     */
    public void setPassword(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>user_center.user.password</code>. 密码, 测试用途明文存储
     */
    public String getPassword() {
        return (String) get(3);
    }

    /**
     * Setter for <code>user_center.user.phone_number</code>. 手机号
     */
    public void setPhoneNumber(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>user_center.user.phone_number</code>. 手机号
     */
    public String getPhoneNumber() {
        return (String) get(4);
    }

    /**
     * Setter for <code>user_center.user.email</code>. 邮箱
     */
    public void setEmail(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>user_center.user.email</code>. 邮箱
     */
    public String getEmail() {
        return (String) get(5);
    }

    /**
     * Setter for <code>user_center.user.header_image</code>. 头像地址
     */
    public void setHeaderImage(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>user_center.user.header_image</code>. 头像地址
     */
    public String getHeaderImage() {
        return (String) get(6);
    }

    /**
     * Setter for <code>user_center.user.sex</code>. 性别 0-男、1-女
     */
    public void setSex(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>user_center.user.sex</code>. 性别 0-男、1-女
     */
    public Byte getSex() {
        return (Byte) get(7);
    }

    /**
     * Setter for <code>user_center.user.status</code>. 用户状态 0-正常、1-禁用
     */
    public void setStatus(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>user_center.user.status</code>. 用户状态 0-正常、1-禁用
     */
    public Byte getStatus() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>user_center.user.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>user_center.user.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>user_center.user.modify_time</code>.
     */
    public void setModifyTime(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>user_center.user.modify_time</code>.
     */
    public LocalDateTime getModifyTime() {
        return (LocalDateTime) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record11 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row11<Long, String, String, String, String, String, String, Byte, Byte, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row11) super.fieldsRow();
    }

    @Override
    public Row11<Long, String, String, String, String, String, String, Byte, Byte, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row11) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return User.USER.ID;
    }

    @Override
    public Field<String> field2() {
        return User.USER.LOGIN_NAME;
    }

    @Override
    public Field<String> field3() {
        return User.USER.NICK_NAME;
    }

    @Override
    public Field<String> field4() {
        return User.USER.PASSWORD;
    }

    @Override
    public Field<String> field5() {
        return User.USER.PHONE_NUMBER;
    }

    @Override
    public Field<String> field6() {
        return User.USER.EMAIL;
    }

    @Override
    public Field<String> field7() {
        return User.USER.HEADER_IMAGE;
    }

    @Override
    public Field<Byte> field8() {
        return User.USER.SEX;
    }

    @Override
    public Field<Byte> field9() {
        return User.USER.STATUS;
    }

    @Override
    public Field<LocalDateTime> field10() {
        return User.USER.CREATE_TIME;
    }

    @Override
    public Field<LocalDateTime> field11() {
        return User.USER.MODIFY_TIME;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getLoginName();
    }

    @Override
    public String component3() {
        return getNickName();
    }

    @Override
    public String component4() {
        return getPassword();
    }

    @Override
    public String component5() {
        return getPhoneNumber();
    }

    @Override
    public String component6() {
        return getEmail();
    }

    @Override
    public String component7() {
        return getHeaderImage();
    }

    @Override
    public Byte component8() {
        return getSex();
    }

    @Override
    public Byte component9() {
        return getStatus();
    }

    @Override
    public LocalDateTime component10() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime component11() {
        return getModifyTime();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getLoginName();
    }

    @Override
    public String value3() {
        return getNickName();
    }

    @Override
    public String value4() {
        return getPassword();
    }

    @Override
    public String value5() {
        return getPhoneNumber();
    }

    @Override
    public String value6() {
        return getEmail();
    }

    @Override
    public String value7() {
        return getHeaderImage();
    }

    @Override
    public Byte value8() {
        return getSex();
    }

    @Override
    public Byte value9() {
        return getStatus();
    }

    @Override
    public LocalDateTime value10() {
        return getCreateTime();
    }

    @Override
    public LocalDateTime value11() {
        return getModifyTime();
    }

    @Override
    public UserRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public UserRecord value2(String value) {
        setLoginName(value);
        return this;
    }

    @Override
    public UserRecord value3(String value) {
        setNickName(value);
        return this;
    }

    @Override
    public UserRecord value4(String value) {
        setPassword(value);
        return this;
    }

    @Override
    public UserRecord value5(String value) {
        setPhoneNumber(value);
        return this;
    }

    @Override
    public UserRecord value6(String value) {
        setEmail(value);
        return this;
    }

    @Override
    public UserRecord value7(String value) {
        setHeaderImage(value);
        return this;
    }

    @Override
    public UserRecord value8(Byte value) {
        setSex(value);
        return this;
    }

    @Override
    public UserRecord value9(Byte value) {
        setStatus(value);
        return this;
    }

    @Override
    public UserRecord value10(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    @Override
    public UserRecord value11(LocalDateTime value) {
        setModifyTime(value);
        return this;
    }

    @Override
    public UserRecord values(Long value1, String value2, String value3, String value4, String value5, String value6, String value7, Byte value8, Byte value9, LocalDateTime value10, LocalDateTime value11) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserRecord
     */
    public UserRecord() {
        super(User.USER);
    }

    /**
     * Create a detached, initialised UserRecord
     */
    public UserRecord(Long id, String loginName, String nickName, String password, String phoneNumber, String email, String headerImage, Byte sex, Byte status, LocalDateTime createTime, LocalDateTime modifyTime) {
        super(User.USER);

        setId(id);
        setLoginName(loginName);
        setNickName(nickName);
        setPassword(password);
        setPhoneNumber(phoneNumber);
        setEmail(email);
        setHeaderImage(headerImage);
        setSex(sex);
        setStatus(status);
        setCreateTime(createTime);
        setModifyTime(modifyTime);
    }
}
