spring:
  datasource:
    url: jdbc:mysql://emall.mysql.database.azure.com:3306/product_center
    username: emall
    password: Q1w2e3r4t5y6
  redis:
    database: 0
    host: sheintest.redis.cache.windows.net
    port: 6379
    password: DFALHzmo7mAkMYxTCrrOqwuepRKLYIEhIAzCaAzmkg4=
    jedis:
      pool:
        enable: true
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1
    connect-timeout: 30000
  zipkin:
    base-url: http://20.171.143.16:9411/
    sleuth:
      sampler:
        probability: 1 # 将采样比例设置为 1.0，也就是全部都需要。默认是0.1也就是10%，一般情况下，10%就够用了
  main:
    allow-circular-references: true
grpc:
  server:
    port: 9091
test:
  mock:
    data: false


