spring:
  datasource:
    url: jdbc:mysql://10.2.0.9:6666/user_center
    username: root
    password: Emallmysql1@
  redis:
    database: 0
    host: 10.1.0.70
    port: 7617
    password: 4L62C7zQZg
    jedis:
      pool:
        enable: true
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: -1
    connect-timeout: 30000
  zipkin:
    base-url: http://20.2.136.248:9411/
    sleuth:
      sampler:
        probability: 1 # 将采样比例设置为 1.0，也就是全部都需要。默认是0.1也就是10%，一般情况下，10%就够用了
  main:
    allow-circular-references: true
grpc:
  server:
    port: 9091
test:
  mock:
    data: false


